title: Rashad Sookram
description: >-
  Writing mostly about Android development.

domain: rsookram.github.io
url: https://rsookram.github.io
baseurl: ""

markdown: kramdown

minima:
  social_links:
    twitter: RashadSookram
    github: rsookram

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - 'vendor'
  - Gemfile
  - Gemfile.lock
  - README.md
